config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'subjects#index'
  resources :subjects, only: [:index, :new, :create, :destroy, :show] do
    resources :comments, only: :create
    collection do
      get 'search'
    end
    member do
      post 'vote1'
      post 'vote2'
      post 'vote3'
    end
  end
  resources :users, only: :show
end

app/models/ans_1.rb
class Ans1 < ApplicationRecord

  validates :user_id, :subject_id, presence: true

  belongs_to :user
  belongs_to :subject

end

app/models/ans_2.rb
class Ans2 < ApplicationRecord

  validates :user_id, :subject_id, presence: true
  
  belongs_to :user
  belongs_to :subject

end

app/models/ans_3.rb
class Ans3 < ApplicationRecord

  validates :user_id, :subject_id, presence: true
  
  belongs_to :user
  belongs_to :subject

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :text, presence: true

  belongs_to :user
  belongs_to :subject
  
end

app/models/subject.rb
class Subject < ApplicationRecord

  validates :title, :user_id,  presence: true

  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :ans_1s, dependent: :destroy
  has_many :ans_2s, dependent: :destroy
  has_many :ans_3s, dependent: :destroy

  def self.search(search)
    if search != ""
      Subject.where('title LIKE(?)', "%#{search}%")
    else
      Subject.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :subjects
  has_many :comments
  has_many :ans_1s 
  has_many :ans_2s
  has_many :ans_3s

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to subject_path(@comment.subject.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, subject_id: params[:subject_id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_subject, only: [:show, :destroy]

  def index
    @subjects = Subject.all.order("created_at DESC")
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @subject.comments.includes(:user)
    ans1s = @subject.ans_1s
    ans2s = @subject.ans_2s
    ans3s = @subject.ans_3s
    count1 = ans1s.count
    count2 = ans2s.count
    count3 = ans3s.count
    @counts = count1 + count2 + count3
    @per1 = ((count1/@counts.to_f) * 100).round(1)
    @per2 = ((count2/@counts.to_f) * 100).round(1)
    @per3 = ((count3/@counts.to_f) * 100).round(1)
  end

  def destroy
    @subject.destroy if @subject.user.id == current_user.id
    redirect_to root_path
  end

  def vote1
    subject_id = vote_params
    ans1 = Ans1.new(subject_id: subject_id, user_id: current_user.id)
    ans1.save
    redirect_to subject_path(subject_id)
  end

  def vote2
    subject_id = vote_params
    ans2 = Ans2.new(subject_id: subject_id, user_id: current_user.id)
    ans2.save
    redirect_to subject_path(subject_id)
  end

  def vote3
    subject_id = vote_params
    ans3 = Ans3.new(subject_id: subject_id, user_id: current_user.id)
    ans3.save
    redirect_to subject_path(subject_id)
  end

  def search
    @subjects = Subject.search(params[:keyword])
  end
    
  private
  
  def subject_params
    params.require(:subject).permit(:title, :text).merge(user_id: current_user.id)
  end

  def vote_params
    params.require(:id)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DistributionApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1 class="header_title"><%= link_to "Distribution", root_path, class: "header_link" %></h1>
      <% if user_signed_in? %>
        <div class="header_nav">
          <%= link_to "新規投稿", new_subject_path, class: "nav_link" %>
          <%= link_to "マイページ", user_path(current_user.id), class: "nav_link" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav_link" %>
        </div>
      <% else %>
        <div class="header_nav">
          <%= link_to "ログイン", new_user_session_path, class: "nav_link" %>
          <%= link_to "新規登録", new_user_registration_path, class: "nav_link" %>
        </div>
      <% end %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/subjects/index.html.erb
<% if @subjects.empty? %>
  <h3 class="info">まだ投稿されていません</h3>
<% else %>
  <%= form_with url: search_subjects_path, local: true, method: :get, class: "search-form" do |f| %>
    <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= f.submit "検索", class: "search-btn" %>
　<% end %>
  <h3 class="info">好きな項目をクリックしてください</h3>
  <div class="contents">
    <% @subjects.each do |subject| %>
      <div class="content"> 
        <%= link_to "#{subject.title}", subject_path(subject.id), class: "content_title" %>
      </div>
    <% end %>
  </div> 
<% end %>

app/views/subjects/new.html.erb
<div class="form_box">
  <h2>新規投稿</h2>
  <div class="from">
    <%= form_with model: @subject, local: true do |f| %>
      <div class="box">
        <div class="form_tag">
          タイトル：
        </div> 
        <%= f.text_area :title, class: "from_text", size: "50" %>
      </div>
      <div class="box">
        <div class="box_tag" >
          詳細説明：
        </div>
        <%= f.text_area :text, class: "form_text", size: "50", placeholder: "(例) A:〇〇　B:〇〇 C:〇〇" %>
      </div>
      <div class="box">
        <%= f.submit "投稿する", class: "from_btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/subjects/search.html.erb
<%= form_with url: search_subjects_path, local: true, method: :get, class: "search-form" do |f| %>
  <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= f.submit "検索", class: "search-btn" %>
<% end %>
<% if @subjects.empty? %>
 <h3 class="info">見つかりませんでした</h3>
<% else %>
  <div class="contents">
    <% @subjects.each do |subject| %>
      <div class="content"> 
        <%= link_to "#{subject.title}", subject_path(subject.id), class: "content_title" %>
      </div>
    <% end %>
  </div> 
<% end %>

app/views/subjects/show.html.erb
<div class="show_box">
  <h3><%= "#{@subject.title}" %></h3>
  <div class="show_text">
    <%= "#{@subject.text}" %>
  </div>
  <div class="del_box">
    <% if user_signed_in? && current_user.id == @subject.user_id%>
      <%= link_to "削除する", subject_path(@subject.id), method: :delete, class: "del" %>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <% unless Ans1.exists?(user_id: current_user.id, subject_id: @subject.id) ||
              Ans2.exists?(user_id: current_user.id, subject_id: @subject.id) ||
              Ans3.exists?(user_id: current_user.id, subject_id: @subject.id) %>
      <div class="post">
        <%= link_to "a", "/subjects/#{@subject.id}/vote1", method: :post, class: "ans" %>
        <%= link_to "b", "/subjects/#{@subject.id}/vote2", method: :post, class: "ans" %>
        <%= link_to "c", "/subjects/#{@subject.id}/vote3", method: :post, class: "ans" %>
      </div>
    <% else %>
       <div class="results">
         <h4 class="call">結果(投票済)</h4>
         <ul>
           <li>
            <span class=mar-20><%= "a: #{@per1}%" %></span>
            <span class=mar-20><%= "b: #{@per2}%" %></span>
                               <%= "c: #{@per3}%" %>
           </li>
           <li><%= "総投票数: #{@counts}票" %></li>
         </ul>
       </div>
    <% end %>
  <% else %>
    <h4 class="call">投票や結果を見るにはログインする必要があります</h4>
  <% end %>
  
  <% if user_signed_in? %>
    <% if Ans1.exists?(user_id: current_user.id, subject_id: @subject.id) ||
          Ans2.exists?(user_id: current_user.id, subject_id: @subject.id) ||
          Ans3.exists?(user_id: current_user.id, subject_id: @subject.id) %>
      <div class="comment_form">
        <%= form_with model: [@subject, @comment], local: true do |f| %>
          <%= f.text_area :text, placeholder: "コメント", size: "50" %>
          <%= f.submit "SEND" %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="comments">
    <h4>コメント一覧</h4>
    <% @comments.each do |comment| %>
      <p>
        <%= link_to comment.user.nickname, user_path(comment.user.id) %>：
        <%= comment.text %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="myp_box">
  <h2><%= "#{@user.nickname}さん" %></h2>
  <div class="info">
    <h3>投稿</h3>
    <% @user.subjects.reverse.each do |subject| %>
      <div class="post">
        <%= link_to "#{subject.title}", subject_path(subject.id), class: "mytext" %>
      </div>
    <% end %>
    <h3>a</h3>
    <% @user.ans_1s.reverse.each do |ans_1| %>
      <div class="vote">
        <%= link_to "#{ans_1.subject.title}", subject_path(ans_1.subject.id), class: "mytext" %>
        <% @user.comments.each do |comment| %>
          <% if comment.subject_id == ans_1.subject.id %>
            (コメント有）<% break %> 
          <% end %>
        <% end %>
      </div>
    <% end %>
    <h3>b</h3>
    <% @user.ans_2s.reverse.each do |ans_2| %>
      <div class="vote">
        <%= link_to "#{ans_2.subject.title}", subject_path(ans_2.subject.id), class: "mytext" %>
        <% @user.comments.each do |comment| %>
          <% if comment.subject_id == ans_2.subject.id %>
            (コメント有）<% break %> 
          <% end %>
        <% end %>
      </div>
    <% end %>
    <h3>c</h3>
    <% @user.ans_3s.reverse.each do |ans_3| %>
      <div class="vote">
        <%= link_to "#{ans_3.subject.title}", subject_path(ans_3.subject.id), class: "mytext" %>
        <% @user.comments.each do |comment| %>
          <% if comment.subject_id == ans_3.subject.id %>
            (コメント有）<% break %> 
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>